### ISSUE TITLE
API error messages are not checked and passed to the user

### ISSUE THREAD

**Issue by valentin-kaiser** [AntonSkrub/GoGit-Integration#17]
If an error occurs when calling the Git API due to incorrect credentials or other reasons, it is not recognizable. There is only an error because the response cannot be converted to the JSON struct `[API] failed unmarshalling the json: json: cannot unmarshal object into Go value of type []gitapi.Repository`.

**Comment by AntonSkrub** [comment]
fixed in commit 095d4e8
