### ISSUE TITLE
Configure multiple users and organizations

### ISSUE THREAD

**Issue by valentin-kaiser** [AntonSkrub/GoGit-Integration#18]
I would like to have the possibility to specify multiple organizations and users in the configuration. Also, the program should determine whether a backup is performed based on the specified users and not on the `CloneUserRepos` flag.
Also, when I create the default configuration, I miss the structure of a user. Unfortunately I can only get this from the README. It would be nice to have a default user in the default configuration as well.

**Comment by AntonSkrub** [comment]
It is possible to configure multiple organizations and users now, but please look at the creation of the cron jobs in the main.go file.
I'm almost sure there is a better way of doing it that what i did there

**Comment by valentin-kaiser** [comment]
> It is possible to configure multiple organizations and users now, but please look at the creation of the cron jobs in the main.go file. I'm almost sure there is a better way of doing it that what i did there

I will review the PR referencing this issue and pay special attention to it.
